### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by thawtes** [back-to/ipk#3]
hi, @back-to 

all files installed and OK for Enigma2.

after install 

telnet command : streamlink -l debug

`root@vuduo2:~# streamlink -l debug
Traceback (most recent call last):
  File "/usr/bin/streamlink", line 6, in <module>
    from streamlink.main import main
ImportError: No module named main
root@vuduo2:~#`

and liveproxy-server not work :(

http%3a//127.0.0.1%3a53422/play/?url=https%253A%252F%252Fwww.euronews.com%252Flive

`root@vuduo2:~# liveproxy-server start
/usr/sbin/liveproxy-server: line 21: kill: (24052) - No such process
Starting service…
 is now running, the PID is 24239
root@vuduo2:~#`

`root@vuduo2:~# liveproxy-server status
Checking liveproxy-server...                      The process appears to be dead but pidfile still exists
root@vuduo2:~#`

please checks and fix its 

my device VU+ DUO2  usage image openATV 6.2

note: livecli worked very well :(

**Comment by back-to** [comment]
@thawtes 
thx for the bug report,

I have a typo at

https://github.com/back-to/ipk/blob/master/source/python-streamlink/usr/bin/streamlink#L6

could you change the line

from

```py
from streamlink.main import main
```

to

```py
from streamlink_cli.main import main
```
you might need to restart the service

or just run

`streamlink -l debug`

and you will see if it's fixed.

---

well it's easier to update streamlink than livecli in the long term

**Comment by thawtes** [comment]
ok thx
i had guessed that
`root@vuduo2:~# streamlink -l debug`
`[cli][info] streamlink is running as root! Be careful!`
`[cli][debug] OS:         Linux-3.13.5-mips-with-glibc2.0`
`[cli][debug] Python:     2.7.13`
`[cli][debug] Streamlink: 0+unknown`
`[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)`
`usage: streamlink [OPTIONS] <URL> [STREAM]`
`Use -h/--help to see the available options or read the manual at https://streamlink.github.io`

but liveproxy-server not work 

there is no reaction, links do not open!

What would you advise me to do to find the problem?

**Comment by back-to** [comment]
@thawtes 

```
[cli][debug] Streamlink: 0+unknown
```

there should be an version, weird whatever.

---

could you run

```
streamlink "https://www.youtube.com/watch?v=a-M_5rGhPdg" -l debug
```

to see if streamlink actually works

if yes

run

```
liveproxy --host 0.0.0.0
```

this will start the version manually in your console

and post the output here

**Comment by back-to** [comment]
ok i think i found the issue for liveproxy a file is missing

**Comment by thawtes** [comment]
streamlink working

`root@vuduo2:~# streamlink "https://www.youtube.com/watch?v=a-M_5rGhPdg" -l debug`
`[cli][info] streamlink is running as root! Be careful!`
`[cli][debug] OS:         Linux-3.13.5-mips-with-glibc2.0`
`[cli][debug] Python:     2.7.13`
`[cli][debug] Streamlink: 0+unknown`
`[cli][debug] Requests(2.18.4), Socks(1.6.7), Websocket(0.47.0)`
`[cli][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=a-M_5rGhPdg`
`[plugin.youtube][debug] get_video_info - 1: Found data`
`[plugin.youtube][debug] This video is live.`
`Available streams: 144p (worst), 240p, 360p, 480p, 720p, 1080p (best)`


liveproxy not work

`root@vuduo2:~# liveproxy --host 0.0.0.0`
`-bash: liveproxy: command not found`
`root@vuduo2:~#`

**Comment by back-to** [comment]
I updated the liveproxy issue

https://github.com/back-to/ipk/raw/master/build/python-liveproxy_0.0.2_all.ipk

I will update streamlink later aswell, but could you test this version.

not sure if you will have to restart or not.

**Comment by back-to** [comment]
and if you used the **resolve** plugin with livecli and you want it with streamlink / liveproxy

you will have to download it

https://raw.githubusercontent.com/back-to/plugins/master/plugins/resolve.py

and put it into `$HOME/.config/streamlink/plugins/` which is `/home/root/.config/streamlink/plugins/`

**Comment by thawtes** [comment]
ok thx its work
`root@vuduo2:~# liveproxy`
`[liveproxy-shared][info] LiveProxy is running as root! Be careful!`
`[liveproxy-main][info] For LiveProxy support visit https://github.com/back-to/liveproxy`
`[liveproxy-main][debug] OS: Linux-3.13.5-mips-with-glibc2.0`
`[liveproxy-main][debug] Python: 2.7.13`
`[liveproxy-main][debug] LiveProxy: 0.0.1`
`[liveproxy-main][debug] Streamlink: 0+unknown`
`[liveproxy-main][debug] Requests(2.18.4), Websocket(0.47.0)`
`[liveproxy-main][info] Starting server: 127.0.0.1 on port 53422`

thank you

**Comment by thawtes** [comment]
https://raw.githubusercontent.com/back-to/plugins/master/plugins/resolve.py

yes i usage

https://raw.githubusercontent.com/back-to/plugins/master/plugins/ *.py mean all files

copy to .../streamlink/plugins/

**Comment by thawtes** [comment]
about  `[cli][debug] Streamlink: 0+unknown`

I always use the last files on github

so maybe you can write 0+unknown

ok?

**Comment by thawtes** [comment]
i usage your streamlink build ipk

`[cli][debug] Streamlink: 0.13.0+18.g3136f96`

so no problem !

I write that there should be no confusion

No problem with your packaging system, do not consider this a problem

thank you again for everything

**Comment by thawtes** [comment]
hello again

`[liveproxy-server][info] User-Agent: Enigma2 HbbTV/1.1.1 (+PVR+RTSP+DL;openATV;;;)`
`[liveproxy-server][info] Client: ('127.0.0.1', 51497)`
`[liveproxy-server][info] Address: localhost.localdomain`
`[liveproxy-server][warning] Plugin path /home/root/.config/streamlink/plugins does not exist or is not a directory!`
`[liveproxy-server][info] Found matching plugin youtube for URL https://www.youtube.com/watch?v=_tqiBzkdsqE`
`[liveproxy-server][info] Available streams: audio_webm, audio_mp4, 144p (worst), 180p, 360p, 720p, 1080p (best)`
`[liveproxy-server][info] Opening stream: 720p (http)`

`**[liveproxy-server][warning] Plugin path /home/root/.config/streamlink/plugins does not exist or is not a directory!**`

this is a problem ?

**Comment by back-to** [comment]
Streamlink is now the same version as https://github.com/streamlink/streamlink

https://github.com/back-to/ipk/raw/master/build/python-streamlink_0.13.0.50_all.ipk

---

> about [cli][debug] Streamlink: 0+unknown
I always use the last files on github

If you just copy the files from github, this is normal.

---

> copy to .../streamlink/plugins/

if this is the normal streamlink folder, you should better use the real folder for custom plugins

```
/home/root/.config/streamlink/plugins
```

https://streamlink.github.io/cli.html#sideloading-plugins

---

```
[liveproxy-server][warning] Plugin path /home/root/.config/streamlink/plugins does not exist or is not a directory!
```

No it's **not a problem**, just a _small warning_ that LiveProxy won't load any custom plugins from this default folder

**Comment by thawtes** [comment]
Thanks again for everything, everything works very well.
Best regards
